name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

  workflow_dispatch:

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v2

      # Step 2: Install Yarn (if not already installed)
      - name: Install Yarn
        run: npm install -g yarn

      # Step 3: Install Vercel CLI using Yarn
      - name: Install Vercel CLI
        run: yarn global add vercel@latest

      # Step 4: Pull Vercel Environment Information for Preview Environment
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Step 5: Build the Project
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # Step 6: Deploy to Vercel (Preview Environment)
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
