name: Add PR Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "GitBot has reviewed your code!"
            });
