name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v2

      # Step 2: Install Yarn (if not already installed)
      - name: Install Yarn
        run: npm install -g yarn

      # Step 3: Install Vercel CLI using Yarn
      - name: Install Vercel CLI
        run: yarn global add vercel@latest

      # Step 4: Authenticate with Vercel
      - name: Authenticate with Vercel
        run: vercel login --token=${{ secrets.VERCEL_TOKEN }}

      # Step 5: Pull Vercel Environment Information
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Step 6: Build the Project
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # Step 7: Deploy to Production
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
